# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
   # useVMManagedIdentity: "false"    # Set to true for using managed identity
   # userAssignedIdentityID: ""      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: openhack-team4-kv 
    tenantId: 4b860e19-212f-436e-a550-a5644e0d0015           # The tenant ID of the key vault
    objects: |
      array: 
        - |
          objectName: SQLPASSWORD          
          objectType: secret                                      
  secretObjects:                             
  - secretName: appsecrets  
    data:
    - key: SQLPASSWORD                          
      objectName: SQLPASSWORD                                        
    type: Opaque 