apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryfiv5480.azurecr.io/tripinsights/tripviewer:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://20.168.147.25/api/user
        - name: TRIPS_API_ENDPOINT
          value: http://20.168.147.25/api/trips
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: tripviewer