apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryfiv5480.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: SQL_USER
          value: sqladminfIv5480
        - name: SQL_SERVER
          value: sqlserverfiv5480.database.windows.net
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: secretsvolume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secretsvolume
        secret:
          secretName: db-secrets
          optional: false # default setting; "mysecret" must exist
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: user-java